---
Title: "Introduction"
Author: "Wava Chan & Isabella Hottenrott"
format: html
---

# Abstract

This project creates a rock-paper-scissors game, where the user plays against the computer. The user would play a move (rock, paper, scissors), the computer would play a move, and then the two would be compared. To accomplish this objective, the project delves into the intricacies of gesture recognition by using a series of LiDAR sensors to identify the user’s gesture of rock, paper, or scissors, and uses an LCD screen to communicate with the user.

The game is initialized and the user is told to place a move. The sensors detect what gesture was played by the user, and simultaneously reports its own choice on the LCD screen. The outcome of the game is reported and displayed on the LCD screen, either win, lose, or draw. The LCD screen then returns to a starting state for the next round. And finally, the user is given an option to move onto the next round, which would likely be more difficult.  
